export default {
  name: 'Nosotros',
  data() {
    return {
      members: [
        {
          img_container_class: 'equipo-img-cont-diff',
          img: `${this.$versionRoot}image/nosotros/flor.png`,
          name: 'Flor González',
          position: 'Fundadora - Vínculo',
          href: 'https://www.instagram.com/flormosenia/',
          social_name: '@flormosenia',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/pablo.png`,
          name: 'Pablo González',
          position: 'Fundador - Introspección',
          href: 'https://www.twitter.com/antecesorcomun/',
          social_name: '@antecesorcomun',
          social_class: 'fab fa-twitter',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/juama.png`,
          name: 'Juama Garrido',
          position: 'Fundador - Líder de diseño',
          href: 'https://www.instagram.com/juamagarrido/',
          social_name: '@juamagarrido',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/nuria.png`,
          name: 'Nuria Cáceres',
          position: 'Vínculo',
          href: 'https://www.instagram.com/nuricaceres/',
          social_name: '@nuricaceres',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/bartolo.png`,
          name: 'Bartolo',
          position: 'Operaciones Especiales',
          href: '',
          social_name: '',
          social_class: 'fas fa-paw',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/laura.png`,
          name: 'Laura González',
          position: 'Líder de desarrollo',
          href: 'https://www.instagram.com/nohaynombredisponible/',
          social_name: '@nohaynombredisponible',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/rodrigo.png`,
          name: 'Rodrigo Catalano',
          position: 'CTO',
          href: 'https://www.instagram.com/dechadou/',
          social_name: '@dechadou',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/javier.png`,
          name: 'Javier Goldschmidt',
          position: 'Fullstack dev',
          href: 'https://www.instagram.com/goljavi/',
          social_name: '@goljavi',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/meli.png`,
          name: 'Meli Wortman',
          position: 'Edición',
          href: 'https://www.facebook.com/melocotonota/',
          social_name: '@melocotonota',
          social_class: 'fab fa-facebook',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/javiers.png`,
          name: 'Javier Sendra',
          position: 'Campañas y Equipos',
          href: 'https://www.twitter.com/pjsendra/',
          social_name: '@pjsendra',
          social_class: 'fab fa-twitter',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/matias.png`,
          name: 'Mathias Schusterman',
          position: 'Comunidades',
          href: 'https://www.instagram.com/mathiaschu/',
          social_name: '@mathiaschu',
          social_class: 'fab fa-instagram',
        },
        {
          img_container_class: 'equipo-img-cont',
          img: `${this.$versionRoot}image/nosotros/facundo.png`,
          name: 'Facundo Álvarez',
          position: 'Fundador',
          href: 'https://www.instagram.com/facuaah/',
          social_name: '@facuaah',
          social_class: 'fab fa-instagram',
        },
      ],
    };
  },
  mounted() {
    setTimeout(() => window.scrollTo(0, 0), 500);
  },
};
